import type { InferredMissionContext } from "./MissionKnowledge";
import {
  renderBulletList,
  renderChecklist,
  renderDependencies,
  renderPipelineDiagram,
} from "./MissionKnowledge";

export function generateClaudeEngineeringPackage(input: {
  context: InferredMissionContext;
  atlasVersion: string;
  atlasBuild: string;
  generatedAt: string;
}): string {
  const { context, atlasVersion, atlasBuild, generatedAt } = input;
  const { card } = context;
  const focusList = card.focus.map((item) => `- ${item}`).join("\n");
  const constraintList = card.constraints.map((item) => `- ${item}`).join("\n") || "- Geen extra constraints opgegeven.";

  return [
    `# Claude Engineering Package — ${card.mission}`,
    "",
    "> **Atlas Mission Orchestrator** — Humans provide intent or Mission ID. Atlas derives everything from the Constitution.",
    "",
    "## Constitution",
    "",
    `- **Constitution ID:** ${context.constitutionId}`,
    `- **Source of truth:** \`${context.constitutionPath}\``,
    `- **North Star alignment:** ${context.northStarEvaluation.advancesNorthStar ? "Yes" : "Review needed"} (${context.northStarEvaluation.score}/10)`,
    "",
    renderBulletList(context.northStarEvaluation.reasons),
    "",
    "## Evolution Engine",
    "",
    `- **Engine ID:** ${context.decisionTrace.evolution?.engineId ?? context.decisionTrace.frameworkId}`,
    `- **North Star aligned:** ${context.decisionTrace.northStarAligned ? "Yes" : "Review needed"} (${context.decisionTrace.northStarScore}/10)`,
    `- **Selected mission:** ${context.decisionTrace.selectedMissionId ?? "none"}`,
    `- **Next best mission:** ${context.decisionTrace.nextBestMissionId ?? "none"}`,
    "",
    context.decisionTrace.selectionRationale,
    "",
    ...(context.decisionTrace.evolution
      ? [
          "### Where are we / where we want to be",
          "",
          `- **Today:** ${context.decisionTrace.evolution.answers.whereAreWeToday}`,
          `- **Target:** ${context.decisionTrace.evolution.answers.whereDoWeWantToBe}`,
          `- **Gaps:** ${context.decisionTrace.evolution.answers.missingCapabilities.join(", ") || "none"}`,
          `- **Highest value:** ${context.decisionTrace.evolution.answers.highestValueCapability ?? "none"}`,
          "",
        ]
      : []),
    "### Evolution steps",
    "",
    ...context.decisionTrace.steps.map(
      (item) => `- **${item.label}** (${item.status}) — ${item.summary}`,
    ),
    "",
    "## Input received",
    "",
    "```",
    card.mission,
    "```",
    "",
    "No additional instructions from ChatGPT are required or expected.",
    "",
    "Humans may express intent (e.g. \"better at reasoning\"); Atlas maps intent to missions via the Constitution.",
    "",
    "## Atlas inference pipeline",
    "",
    "```",
    renderPipelineDiagram(),
    "```",
    "",
    "## Mission (from Registry)",
    "",
    `- **Mission ID:** ${card.mission}`,
    `- **Title:** ${card.title}`,
    `- **Registry source:** ${context.registryEntry.sourcePath}`,
    `- **Template:** ${card.templateId}`,
    `- **Atlas:** ${atlasVersion} (${atlasBuild})`,
    `- **Generated:** ${generatedAt}`,
    "",
    "## Goal",
    "",
    card.goal,
    "",
    "## Implementation focus",
    "",
    focusList,
    "",
    "## Constraints",
    "",
    constraintList,
    "",
    "## Engineering Standards (inferred)",
    "",
    renderBulletList(context.engineeringStandards),
    "",
    "## North Star (inferred)",
    "",
    renderBulletList(context.northStarGoals),
    "",
    "## Architecture Rules (inferred)",
    "",
    renderBulletList(context.architectureRules),
    "",
    "## Mission Dependencies (inferred)",
    "",
    renderDependencies(context.dependencies),
    "",
    "## Definition of Done",
    "",
    renderChecklist(context.definitionOfDone),
    "",
    "## Validation Plan",
    "",
    renderBulletList(context.validationChecks),
    "",
    "## Commands to run before finishing",
    "",
    "```bash",
    `npm run atlas:mission ${card.mission}`,
    "npm run atlas:audit",
    "npm run atlas:audit -- --strict",
    "npx tsc --noEmit",
    "npm run atlas:health",
    "```",
    "",
    "## Claude instructions",
    "",
    "1. Implement this mission under `src/atlas/` using the focus areas above.",
    "2. Follow all Engineering Standards, Architecture Rules, and Constraints.",
    "3. Respect Mission Dependencies — do not rebuild upstream missions unless required.",
    "4. Do **not** write a new Architecture Brief — Atlas already generated the engineering package.",
    "5. Keep changes small, TypeScript strict, and registry-aligned.",
    "6. Complete the Definition of Done checklist before marking the mission done.",
    "7. Run validation commands and ensure Atlas Auditor release decision is APPROVED or APPROVED_WITH_NOTES.",
    "8. Fill in `release-notes.md` after implementation.",
    "",
    "## Success criteria",
    "",
    card.success,
    "",
    "---",
    "",
    `_Generated by Atlas Mission Orchestrator · ${generatedAt}_`,
    "",
  ].join("\n");
}
