import type { MissionCard } from "../brief-generator/MissionCard";

export function generateReleaseNotesDocument(card: MissionCard, atlasVersion: string, atlasBuild: string): string {
  return [
    `# Release Notes — ${card.mission}`,
    "",
    `- Mission · **${card.mission}**`,
    `- Title · **${card.title}**`,
    `- Atlas · ${atlasVersion} (${atlasBuild})`,
    `- Status · **Pending implementation**`,
    "",
    "## Summary",
    "",
    "_Fill in after sprint completion._",
    "",
    card.goal,
    "",
    "## Delivered",
    "",
    "- [ ] _List completed deliverables_",
    "",
    "## Changed files",
    "",
    "- _List new and modified files_",
    "",
    "## Validation",
    "",
    "- [ ] npm run atlas:mission " + card.mission,
    "- [ ] npm run atlas:audit -- --strict",
    "- [ ] npx tsc --noEmit",
    "",
    "## Release decision",
    "",
    "- Status · _APPROVED / APPROVED_WITH_NOTES / BLOCKED_",
    "- Push · _YES / NO_",
    "",
    "## Follow-up",
    "",
    "- _Open items for next mission_",
    "",
  ].join("\n");
}
