import type { ModelProfile, ModelProfileSeed } from "./types";
import { tryGetActiveModule } from "@/atlas/publishing/plugin/registry";

const ROUTING_DEFAULTS: Pick<ModelProfile, "priority" | "rankScore" | "estimatedCostPer1kTokens"> = {
  priority: 100,
  rankScore: 70,
  estimatedCostPer1kTokens: 0.002,
};

const MODEL_ROUTING: Partial<Record<string, Partial<ModelProfile>>> = {
  "claude-sonnet-5": { priority: 7, rankScore: 97, fallbackModelId: "atlas-mock", estimatedCostPer1kTokens: 0.003 },
  "claude-haiku-4-5": { priority: 9, rankScore: 93, fallbackModelId: "atlas-mock", estimatedCostPer1kTokens: 0.001 },
  "claude-sonnet": { priority: 10, rankScore: 95, fallbackModelId: "gpt-4o", estimatedCostPer1kTokens: 0.003 },
  "claude-3-5-sonnet-latest": { priority: 8, rankScore: 96, fallbackModelId: "atlas-mock", estimatedCostPer1kTokens: 0.003 },
  "gpt-4o": { priority: 20, rankScore: 92, fallbackModelId: "gemini-pro", estimatedCostPer1kTokens: 0.0025 },
  "gemini-pro": { priority: 30, rankScore: 90, fallbackModelId: "mistral-large", estimatedCostPer1kTokens: 0.002 },
  perplexity: { priority: 15, rankScore: 88, estimatedCostPer1kTokens: 0.0025 },
  "mistral-large": { priority: 40, rankScore: 86, estimatedCostPer1kTokens: 0.0015 },
  "grok-beta": { priority: 45, rankScore: 84, estimatedCostPer1kTokens: 0.002 },
  "openrouter-auto": { priority: 50, rankScore: 82, estimatedCostPer1kTokens: 0.002 },
  "deepseek-chat": { priority: 35, rankScore: 85, estimatedCostPer1kTokens: 0.001 },
  deepl: { priority: 12, rankScore: 93, estimatedCostPer1kTokens: 0.0012 },
  "openai-dalle": { priority: 25, rankScore: 90, estimatedCostPer1kTokens: 0.02 },
  "atlas-stub": { priority: 999, rankScore: 50, estimatedCostPer1kTokens: 0 },
  "atlas-mock": { priority: 998, rankScore: 50, estimatedCostPer1kTokens: 0 },
};

function enrichModelProfile(seed: ModelProfileSeed): ModelProfile {
  return {
    ...ROUTING_DEFAULTS,
    ...seed,
    ...(MODEL_ROUTING[seed.id] ?? {}),
  };
}

/** Model metadata — vendor names only live here, never in agents or modules. */
export const MODEL_PROFILES: Record<string, ModelProfileSeed> = {
  "claude-sonnet-5": {
    id: "claude-sonnet-5",
    providerId: "claude",
    name: "Claude Sonnet 5",
    vendor: "Anthropic",
    strengths: ["Copywriting", "Long context", "Structured output", "Reasoning", "Fact checking"],
    costTier: "medium",
    speedTier: "fast",
    qualityTier: "best",
    latencyMs: 1800,
    contextWindow: 1_000_000,
    supportedLanguages: ["nl", "en", "de", "fr", "es", "it"],
    supportedOutputs: ["text", "markdown", "json", "validation", "score"],
    supportedMedia: ["text"],
    available: true,
  },
  "claude-haiku-4-5": {
    id: "claude-haiku-4-5",
    providerId: "claude",
    name: "Claude Haiku 4.5",
    vendor: "Anthropic",
    strengths: ["Speed", "Cost efficiency", "Structured output"],
    costTier: "low",
    speedTier: "fast",
    qualityTier: "excellent",
    latencyMs: 900,
    contextWindow: 200_000,
    supportedLanguages: ["nl", "en", "de", "fr", "es", "it"],
    supportedOutputs: ["text", "markdown", "json", "validation"],
    supportedMedia: ["text"],
    available: true,
  },
  "claude-sonnet": {
    id: "claude-sonnet",
    providerId: "claude",
    name: "Claude Sonnet",
    vendor: "Anthropic",
    strengths: ["Copywriting", "Long context", "Editorial quality", "Nuance"],
    costTier: "medium",
    speedTier: "balanced",
    qualityTier: "best",
    latencyMs: 2200,
    contextWindow: 200_000,
    supportedLanguages: ["nl", "en", "de", "fr", "es", "it"],
    supportedOutputs: ["text", "markdown", "json", "validation"],
    supportedMedia: ["text"],
    available: true,
  },
  "claude-3-5-sonnet-latest": {
    id: "claude-3-5-sonnet-latest",
    providerId: "claude",
    name: "Claude 3.5 Sonnet (retired — routes to Claude Sonnet 5)",
    vendor: "Anthropic",
    strengths: ["Copywriting", "Long context", "Structured output", "Fact checking"],
    costTier: "medium",
    speedTier: "balanced",
    qualityTier: "best",
    latencyMs: 2200,
    contextWindow: 200_000,
    supportedLanguages: ["nl", "en", "de", "fr", "es", "it"],
    supportedOutputs: ["text", "markdown", "json", "validation", "score"],
    supportedMedia: ["text"],
    available: true,
  },
  "gpt-4o": {
    id: "gpt-4o",
    providerId: "openai",
    name: "GPT-4o",
    vendor: "OpenAI",
    strengths: ["SEO", "Structured output", "Translation", "All-round text"],
    costTier: "medium",
    speedTier: "fast",
    qualityTier: "excellent",
    latencyMs: 1800,
    contextWindow: 128_000,
    supportedLanguages: ["nl", "en", "de", "fr", "es", "it"],
    supportedOutputs: ["text", "markdown", "json", "translation", "validation", "score"],
    supportedMedia: ["text", "image"],
    available: true,
  },
  "gemini-pro": {
    id: "gemini-pro",
    providerId: "gemini",
    name: "Gemini Pro",
    vendor: "Google",
    strengths: ["Science", "Fact checking", "Multilingual", "Research"],
    costTier: "medium",
    speedTier: "balanced",
    qualityTier: "excellent",
    latencyMs: 2000,
    contextWindow: 1_000_000,
    supportedLanguages: ["nl", "en", "de", "fr", "es", "it"],
    supportedOutputs: ["text", "markdown", "json", "research", "validation", "translation"],
    supportedMedia: ["text", "image"],
    available: true,
  },
  perplexity: {
    id: "perplexity",
    providerId: "perplexity",
    name: "Perplexity Sonar",
    vendor: "Perplexity",
    strengths: ["Research", "Current sources", "Fact checking"],
    costTier: "medium",
    speedTier: "fast",
    qualityTier: "excellent",
    latencyMs: 2500,
    contextWindow: 127_000,
    supportedLanguages: ["nl", "en", "de", "fr"],
    supportedOutputs: ["research", "text", "markdown", "validation"],
    supportedMedia: ["text"],
    available: true,
  },
  "deepseek-chat": {
    id: "deepseek-chat",
    providerId: "deepseek",
    name: "DeepSeek Chat",
    vendor: "DeepSeek",
    strengths: ["Reasoning", "Cost efficiency", "Structured JSON"],
    costTier: "low",
    speedTier: "fast",
    qualityTier: "excellent",
    latencyMs: 1600,
    contextWindow: 64_000,
    supportedLanguages: ["nl", "en", "de", "fr", "es", "it"],
    supportedOutputs: ["text", "markdown", "json", "validation"],
    supportedMedia: ["text"],
    available: true,
  },
  "openai-dalle": {
    id: "openai-dalle",
    providerId: "openai",
    name: "OpenAI Images",
    vendor: "OpenAI",
    strengths: ["Hero visuals", "Product photography", "Consistent style"],
    costTier: "medium",
    speedTier: "balanced",
    qualityTier: "excellent",
    latencyMs: 8000,
    contextWindow: 0,
    supportedLanguages: ["en"],
    supportedOutputs: ["image"],
    supportedMedia: ["image"],
    available: true,
  },
  deepl: {
    id: "deepl",
    providerId: "deepl",
    name: "DeepL",
    vendor: "DeepL",
    strengths: ["Translation", "Natural Dutch", "EU languages"],
    costTier: "low",
    speedTier: "fast",
    qualityTier: "best",
    latencyMs: 900,
    contextWindow: 0,
    supportedLanguages: ["nl", "en", "de", "fr", "es", "it"],
    supportedOutputs: ["translation"],
    supportedMedia: ["text"],
    available: true,
  },
  "atlas-stub": {
    id: "atlas-stub",
    providerId: "stub",
    name: "Atlas Stub",
    vendor: "Atlas",
    strengths: ["Offline development", "Pipeline testing", "Deterministic output"],
    costTier: "low",
    speedTier: "fast",
    qualityTier: "good",
    latencyMs: 10,
    contextWindow: 0,
    supportedLanguages: ["nl", "en", "de", "fr", "es", "it"],
    supportedOutputs: ["text", "markdown", "json", "image", "research", "translation", "validation", "score"],
    supportedMedia: ["text", "image"],
    available: true,
  },
  "atlas-mock": {
    id: "atlas-mock",
    providerId: "mock",
    name: "Atlas Mock",
    vendor: "Atlas",
    strengths: ["Deterministic tests", "CI pipelines", "Offline mode"],
    costTier: "low",
    speedTier: "fast",
    qualityTier: "good",
    latencyMs: 5,
    contextWindow: 0,
    supportedLanguages: ["nl", "en", "de", "fr", "es", "it"],
    supportedOutputs: ["text", "markdown", "json", "image", "research", "translation", "validation", "score"],
    supportedMedia: ["text", "image"],
    available: true,
  },
  "mistral-large": {
    id: "mistral-large",
    providerId: "mistral",
    name: "Mistral Large",
    vendor: "Mistral",
    strengths: ["Reasoning", "Multilingual", "Structured output"],
    costTier: "medium",
    speedTier: "fast",
    qualityTier: "excellent",
    latencyMs: 1700,
    contextWindow: 128_000,
    supportedLanguages: ["nl", "en", "de", "fr", "es", "it"],
    supportedOutputs: ["text", "markdown", "json", "validation"],
    supportedMedia: ["text"],
    available: true,
  },
  "grok-beta": {
    id: "grok-beta",
    providerId: "grok",
    name: "Grok Beta",
    vendor: "xAI",
    strengths: ["Fast reasoning", "General text", "Structured JSON"],
    costTier: "medium",
    speedTier: "fast",
    qualityTier: "excellent",
    latencyMs: 1900,
    contextWindow: 131_072,
    supportedLanguages: ["nl", "en", "de", "fr", "es", "it"],
    supportedOutputs: ["text", "markdown", "json", "research"],
    supportedMedia: ["text"],
    available: true,
  },
  "openrouter-auto": {
    id: "openrouter-auto",
    providerId: "openrouter",
    name: "OpenRouter Auto",
    vendor: "OpenRouter",
    strengths: ["Multi-vendor routing", "Fallback aggregation", "Cost optimization"],
    costTier: "medium",
    speedTier: "balanced",
    qualityTier: "excellent",
    latencyMs: 2100,
    contextWindow: 200_000,
    supportedLanguages: ["nl", "en", "de", "fr", "es", "it"],
    supportedOutputs: ["text", "markdown", "json", "translation", "validation", "score"],
    supportedMedia: ["text", "image"],
    available: true,
  },
};

function getAllModelProfiles(): Record<string, ModelProfile> {
  const module = tryGetActiveModule();
  const merged: Record<string, ModelProfileSeed> = {
    ...MODEL_PROFILES,
    ...(module?.additionalModelProfiles ?? {}),
  };

  return Object.fromEntries(Object.entries(merged).map(([id, seed]) => [id, enrichModelProfile(seed)]));
}

export function getModelProfile(modelId: string): ModelProfile | undefined {
  return getAllModelProfiles()[modelId];
}

export function listModelProfiles(): ModelProfile[] {
  return Object.values(getAllModelProfiles());
}

export function listAvailableModels(): ModelProfile[] {
  return listModelProfiles().filter((profile) => profile.available);
}

export function getModelsForProvider(providerId: string): ModelProfile[] {
  return listModelProfiles().filter((profile) => profile.providerId === providerId);
}
