import type { KnowledgeArticleInput } from "@/types/knowledgeArticleInput";

/** Catalog articles — techniques, starter, science and related categories. */
export const catalogArticles: KnowledgeArticleInput[] = [
  {
    slug: "gluten",
    categoryId: "bakwetenschap",
    title: "Gluten",
    libraryOrder: 1,
  },
  {
    slug: "glutenontwikkeling",
    categoryId: "bakwetenschap",
    title: "Glutenontwikkeling",
    libraryOrder: 2,
  },
  {
    slug: "eiwitten",
    categoryId: "bakwetenschap",
    title: "Eiwitten",
    libraryOrder: 3,
  },
  {
    slug: "enzymen",
    categoryId: "bakwetenschap",
    title: "Enzymen",
    libraryOrder: 4,
  },
  {
    slug: "ash-content",
    categoryId: "bakwetenschap",
    title: "Ash-content",
    libraryOrder: 5,
  },
  {
    slug: "w-waarde",
    categoryId: "bakwetenschap",
    title: "W-waarde",
    libraryOrder: 6,
  },
  {
    slug: "falling-number",
    categoryId: "bakwetenschap",
    title: "Falling Number",
    libraryOrder: 7,
  },
  {
    slug: "osmose",
    categoryId: "bakwetenschap",
    title: "Osmose",
    libraryOrder: 8,
  },
  {
    slug: "gist",
    categoryId: "bakwetenschap",
    title: "Gist",
    libraryOrder: 9,
  },
  {
    slug: "melkzuurbacterien",
    categoryId: "bakwetenschap",
    title: "Melkzuurbacteriën",
    libraryOrder: 10,
  },
  {
    slug: "maillardreactie",
    categoryId: "bakwetenschap",
    title: "Maillardreactie",
    libraryOrder: 11,
  },
  {
    slug: "karamellisatie",
    categoryId: "bakwetenschap",
    title: "Karamellisatie",
    libraryOrder: 12,
  },
  {
    slug: "bulkfermentatie",
    categoryId: "fermentatie",
    title: "Bulkfermentatie",
    libraryOrder: 1,
  },
  {
    slug: "narijs",
    categoryId: "fermentatie",
    title: "Narijs",
    libraryOrder: 2,
  },
  {
    slug: "cold-proof",
    categoryId: "fermentatie",
    title: "Cold Proof",
    libraryOrder: 3,
  },
  {
    slug: "warm-fermenteren",
    categoryId: "fermentatie",
    title: "Warm fermenteren",
    libraryOrder: 4,
  },
  {
    slug: "overproof",
    categoryId: "fermentatie",
    title: "Overproof",
    libraryOrder: 5,
  },
  {
    slug: "underproof",
    categoryId: "fermentatie",
    title: "Underproof",
    libraryOrder: 6,
  },
  {
    slug: "fermentatieschemas",
    categoryId: "fermentatie",
    title: "Fermentatieschema\\'s",
    libraryOrder: 7,
  },
  {
    slug: "hydratatie",
    categoryId: "hydratatie",
    title: "Hydratatie",
    libraryOrder: 1,
  },
  {
    slug: "bakers-percentage",
    categoryId: "hydratatie",
    title: "Baker\\'s Percentage",
    libraryOrder: 2,
  },
  {
    slug: "waterabsorptie",
    categoryId: "hydratatie",
    title: "Waterabsorptie",
    libraryOrder: 3,
  },
  {
    slug: "hoge-hydratatie",
    categoryId: "hydratatie",
    title: "Hoge hydratatie",
    libraryOrder: 4,
  },
  {
    slug: "lage-hydratatie",
    categoryId: "hydratatie",
    title: "Lage hydratatie",
    libraryOrder: 5,
  },
  {
    slug: "hydratatie-berekenen",
    categoryId: "hydratatie",
    title: "Hydratatie berekenen",
    libraryOrder: 6,
  },
  {
    slug: "wat-is-een-starter",
    categoryId: "starter",
    title: "Wat is een starter?",
    libraryOrder: 1,
  },
  {
    slug: "starter-voeden",
    categoryId: "starter",
    title: "Starter voeden",
    libraryOrder: 2,
  },
  {
    slug: "starter-activeren",
    categoryId: "starter",
    title: "Starter activeren",
    libraryOrder: 3,
  },
  {
    slug: "starter-bewaren",
    categoryId: "starter",
    title: "Starter bewaren",
    libraryOrder: 4,
  },
  {
    slug: "starter-op-piek-herkennen",
    categoryId: "starter",
    title: "Starter op piek herkennen",
    libraryOrder: 5,
  },
  {
    slug: "starterhydratie",
    categoryId: "starter",
    title: "Starterhydratie",
    libraryOrder: 6,
  },
  {
    slug: "slappe-starter",
    categoryId: "starter",
    title: "Slappe starter",
    libraryOrder: 7,
  },
  {
    slug: "zure-starter",
    categoryId: "starter",
    title: "Zure starter",
    libraryOrder: 8,
  },
  {
    slug: "starter-redden",
    categoryId: "starter",
    title: "Starter redden",
    libraryOrder: 9,
  },
  {
    slug: "handmatig-mengen",
    categoryId: "technieken",
    title: "Handmatig mengen",
    libraryOrder: 1,
  },
  {
    slug: "machinaal-kneden",
    categoryId: "technieken",
    title: "Machinaal kneden",
    libraryOrder: 2,
  },
  {
    slug: "autolyse",
    categoryId: "technieken",
    title: "Autolyse",
    libraryOrder: 3,
  },
  {
    slug: "fermentolyse",
    categoryId: "technieken",
    title: "Fermentolyse",
    libraryOrder: 4,
  },
  {
    slug: "stretch-and-fold",
    categoryId: "technieken",
    title: "Stretch & Fold",
    libraryOrder: 5,
  },
  {
    slug: "coil-fold",
    categoryId: "technieken",
    title: "Coil Fold",
    libraryOrder: 6,
  },
  {
    slug: "slap-and-fold",
    categoryId: "technieken",
    title: "Slap & Fold",
    libraryOrder: 7,
  },
  {
    slug: "lamineren",
    categoryId: "technieken",
    title: "Lamineren",
    libraryOrder: 8,
  },
  {
    slug: "bassinage",
    categoryId: "technieken",
    title: "Bassinage",
    libraryOrder: 9,
  },
  {
    slug: "preshape",
    categoryId: "technieken",
    title: "Preshape",
    libraryOrder: 10,
  },
  {
    slug: "final-shape",
    categoryId: "technieken",
    title: "Final Shape",
    libraryOrder: 11,
  },
  {
    slug: "boule-vormen",
    categoryId: "technieken",
    title: "Boule vormen",
    libraryOrder: 12,
  },
  {
    slug: "batard-vormen",
    categoryId: "technieken",
    title: "Batard vormen",
    libraryOrder: 13,
  },
  {
    slug: "banneton-gebruiken",
    categoryId: "technieken",
    title: "Banneton gebruiken",
    libraryOrder: 14,
  },
  {
    slug: "scoren",
    categoryId: "technieken",
    title: "Scoren",
    libraryOrder: 15,
  },
  {
    slug: "ovenspring-creeren",
    categoryId: "technieken",
    title: "Ovenspring creëren",
    libraryOrder: 16,
  },
  {
    slug: "dutch-oven-bakken",
    categoryId: "technieken",
    title: "Dutch Oven bakken",
    libraryOrder: 17,
  },
  {
    slug: "pizza-uitrekken",
    categoryId: "technieken",
    title: "Pizza uitrekken",
    libraryOrder: 18,
  },
  {
    slug: "pizza-lanceren",
    categoryId: "technieken",
    title: "Pizza lanceren",
    libraryOrder: 19,
  },
  {
    slug: "pizza-draaien",
    categoryId: "technieken",
    title: "Pizza draaien",
    libraryOrder: 20,
  },
  {
    slug: "pizza-bakken-op-staal",
    categoryId: "technieken",
    title: "Pizza bakken op staal",
    libraryOrder: 21,
  },
  {
    slug: "pizza-bakken-op-steen",
    categoryId: "technieken",
    title: "Pizza bakken op steen",
    libraryOrder: 22,
  },
  {
    slug: "deegtemperatuur",
    categoryId: "temperaturen",
    title: "Deegtemperatuur (DDT)",
    libraryOrder: 1,
  },
  {
    slug: "watertemperatuur-berekenen",
    categoryId: "temperaturen",
    title: "Watertemperatuur berekenen",
    libraryOrder: 2,
  },
  {
    slug: "oventemperaturen",
    categoryId: "temperaturen",
    title: "Oventemperaturen",
    libraryOrder: 3,
  },
  {
    slug: "temperatuur-fermentatie",
    categoryId: "temperaturen",
    title: "Fermentatietemperaturen",
    libraryOrder: 4,
  },
  {
    slug: "kamertemperatuur",
    categoryId: "temperaturen",
    title: "Kamertemperatuur",
    libraryOrder: 5,
  },
  {
    slug: "koelkast-fermentatie-temperatuur",
    categoryId: "temperaturen",
    title: "Koelkast fermentatie",
    libraryOrder: 6,
  },
];
