import type { ControlSnapshot } from "./types";

export function createMockControlSnapshot(): ControlSnapshot {
  return {
    collectedAt: new Date().toISOString(),
    overview: {
      companyHealthScore: 86,
      companyHealthLabel: "Strong",
      activeAgents: 6,
      activeBusinesses: 3,
      openBlockers: 2,
      pendingApprovals: 1,
      activeInitiatives: 4,
      platformStatus: "healthy",
      platformStatusLabel: "Operational",
      recommendedNextAction:
        "Approve the Branch Director Debrief for STUDIO-002, then advance CONTROL-001 to make Atlas Control the daily command center.",
    },
    agents: [
      {
        id: "branch-director",
        name: "Branch Director",
        role: "Strategic routing & CEO advice",
        status: "active",
        statusLabel: "Active",
        currentFocus: "CEO workflow debrief and next initiative selection",
      },
      {
        id: "engineering-orchestrator",
        name: "Engineering Orchestrator",
        role: "Execution packages & missions",
        status: "active",
        statusLabel: "Active",
        currentFocus: "CONTROL-001 architecture brief",
      },
      {
        id: "quality-auditor",
        name: "Quality Auditor",
        role: "Branch Director Review",
        status: "active",
        statusLabel: "Active",
        currentFocus: "Release readiness for Studio modules",
      },
      {
        id: "capability-advisor",
        name: "Capability Advisor",
        role: "Roadmap intelligence",
        status: "idle",
        statusLabel: "Standby",
        currentFocus: "Monitoring capability gaps after brain-005",
      },
      {
        id: "operations-coordinator",
        name: "Operations Coordinator",
        role: "Runtime & platform routing",
        status: "active",
        statusLabel: "Active",
        currentFocus: "Studio and app runtime separation",
      },
      {
        id: "memory-curator",
        name: "Memory Curator",
        role: "Context & session continuity",
        status: "idle",
        statusLabel: "Standby",
        currentFocus: "Session restore for Atlas Control landing",
      },
    ],
    platformHealth: {
      overall: "healthy",
      overallLabel: "Platform healthy",
      atlasCore: "healthy",
      studio: "healthy",
      intelligence: "attention",
      workflows: "healthy",
      detail: "All core systems operational. Intelligence layer has follow-up notes, not blockers.",
    },
    businesses: [
      {
        id: "robbert-ai",
        name: "Robbert AI",
        type: "Platform company",
        status: "active",
        statusLabel: "Primary focus",
        summary: "Atlas OS, Studio, and autonomous execution stack",
      },
      {
        id: "atlas-studio",
        name: "Atlas Studio",
        type: "Operating product",
        status: "active",
        statusLabel: "In development",
        summary: "CEO command center, workflows, and Branch Director surfaces",
      },
      {
        id: "doughbert",
        name: "Doughbert",
        type: "Consumer app",
        status: "healthy",
        statusLabel: "Running",
        summary: "Reference app on separate runtime — not the Studio focus",
      },
    ],
    blockers: [
      {
        id: "blocker-1",
        title: "CEO continue decision must not reset after publish",
        severity: "medium",
        area: "CEO Workflow",
        owner: "Branch Director",
      },
      {
        id: "blocker-2",
        title: "Studio default landing still points away from command center",
        severity: "low",
        area: "Atlas Control",
        owner: "Operations Coordinator",
      },
    ],
    approvals: [
      {
        id: "approval-1",
        title: "Release STUDIO-002 Branch Director Debrief Flow",
        type: "release",
        requestedBy: "Branch Director",
        urgency: "normal",
      },
    ],
    initiatives: [
      {
        id: "CONTROL-001",
        title: "Atlas Control Foundation",
        phase: "In progress",
        progress: 72,
        status: "active",
      },
      {
        id: "STUDIO-002",
        title: "Branch Director Debrief Flow",
        phase: "Review",
        progress: 94,
        status: "attention",
      },
      {
        id: "DX-003",
        title: "Separate App and Studio Launchers",
        phase: "Completed",
        progress: 100,
        status: "healthy",
      },
      {
        id: "BRAIN-005",
        title: "Capability Registry & Roadmap Intelligence",
        phase: "Completed",
        progress: 100,
        status: "healthy",
      },
    ],
    branchDirectorAdvice: {
      headline: "Make Atlas Control the daily entry point",
      summary:
        "Robbert, the platform is stable enough to shift from feature screens to a single executive command center. Prioritize CONTROL-001, then return to CEO Workflow only when a release or debrief requires your decision.",
      recommendedInitiative: "CONTROL-001 · Atlas Control Foundation",
      confidence: 92,
      rationale: [
        "Studio and app now run independently — safe to optimize for daily oversight.",
        "Pending approvals and active initiatives are visible but scattered across routes.",
        "A unified control surface reduces context switching before the next strategic sprint.",
      ],
    },
  };
}
