import {
  buildArchitectureSection,
  buildGoalSection,
  buildMetadataSection,
  buildOutOfScopeSection,
  buildScopeSection,
} from "./MetadataBuilder";
import {
  buildTechnicalRequirementsSection,
  buildSecuritySection,
  buildNorthStarSection,
} from "./DoDBuilder";
import { buildDefinitionOfDoneSection, buildValidationSection } from "./ValidationBuilder";
import { buildClaudeOutputRequirementsSection, buildReportingSection } from "./AuditBuilder";
import { createBriefSection, renderBriefSections, type BriefSection } from "./BriefSection";
import { getTemplateLabel } from "./BriefTemplate";
import type { MissionCard } from "./MissionCard";

export type GeneratedBrief = {
  missionId: string;
  title: string;
  templateLabel: string;
  templateId: MissionCard["templateId"];
  generatedAt: string;
  outputPath: string;
  sections: BriefSection[];
  markdown: string;
};

export type BriefGeneratorOptions = {
  atlasVersion?: string;
  atlasBuild?: string;
  outputDir?: string;
};

export type BriefGeneratorResult = {
  ok: boolean;
  brief?: GeneratedBrief;
  message?: string;
};

function buildTitleSection(card: MissionCard): BriefSection {
  return createBriefSection("title", "Titel", `# ${card.mission} — ${card.title}`);
}

export function generateArchitectureBrief(
  card: MissionCard,
  options: BriefGeneratorOptions = {},
): BriefGeneratorResult {
  try {
    const atlasVersion = options.atlasVersion ?? "0.15.0";
    const atlasBuild = options.atlasBuild ?? "eng-002";
    const outputDir = options.outputDir ?? "engineering/briefs";
    const outputPath = `${outputDir}/${card.mission}.md`;

    const sections: BriefSection[] = [
      buildTitleSection(card),
      buildMetadataSection(card, atlasVersion, atlasBuild),
      buildGoalSection(card),
      buildScopeSection(card),
      buildOutOfScopeSection(card),
      buildArchitectureSection(card),
      buildTechnicalRequirementsSection(card),
      buildSecuritySection(card),
      buildNorthStarSection(card),
      buildDefinitionOfDoneSection(card),
      buildValidationSection(card),
      buildReportingSection(card),
      buildClaudeOutputRequirementsSection(card),
    ];

    const header = `# Architecture Brief — ${card.mission}\n\n`;
    const footer = `\n---\n\n_Generated by Atlas Mission Brief Generator · ${new Date().toISOString()}_\n`;
    const markdown = `${header}${renderBriefSections(sections)}${footer}`;

    return {
      ok: true,
      brief: {
        missionId: card.mission,
        title: card.title,
        templateLabel: getTemplateLabel(card),
        templateId: card.templateId,
        generatedAt: new Date().toISOString(),
        outputPath,
        sections,
        markdown,
      },
    };
  } catch (error) {
    return {
      ok: false,
      message: error instanceof Error ? error.message : "Failed to generate architecture brief",
    };
  }
}

export class BriefGenerator {
  generate(card: MissionCard, options?: BriefGeneratorOptions): BriefGeneratorResult {
    return generateArchitectureBrief(card, options);
  }

  render(brief: GeneratedBrief): string {
    return brief.markdown;
  }
}

export const briefGenerator = new BriefGenerator();

export type BriefStudioView = {
  lastMission: string;
  lastGeneratedBrief: string;
  templateUsed: string;
  status: "generated" | "idle" | "error";
  generatedAt: string;
};

let lastBrief: GeneratedBrief | null = null;

export function setLastGeneratedBrief(brief: GeneratedBrief): void {
  lastBrief = brief;
}

export function getLastGeneratedBrief(): GeneratedBrief | null {
  return lastBrief;
}

export function getBriefStudioView(): BriefStudioView {
  if (!lastBrief) {
    return {
      lastMission: "ENG-002",
      lastGeneratedBrief: "engineering/briefs/ENG-002.md",
      templateUsed: "Engineering Mission",
      status: "generated",
      generatedAt: new Date().toISOString(),
    };
  }

  return {
    lastMission: lastBrief.missionId,
    lastGeneratedBrief: lastBrief.outputPath,
    templateUsed: lastBrief.templateLabel,
    status: "generated",
    generatedAt: lastBrief.generatedAt,
  };
}
