import type { IntelligenceAnalyzer } from "../engine/types";
import type { AnalyzerResult, IntelligenceContext } from "../types";
import { listContentGaps } from "../content-gaps/store";
import { listQualityScores } from "../quality-scores/store";
import { storeAiSuggestion } from "./store";
import type { AiSuggestionsReport } from "./types";

export const aiSuggestionsAnalyzer: IntelligenceAnalyzer<AiSuggestionsReport> = {
  id: "ai-suggestions.synthesizer",
  category: "ai-suggestions",
  label: "AI Suggestion Synthesizer",

  analyze(context): AnalyzerResult<AiSuggestionsReport> {
    const moduleId = context.scope.moduleId;
    const generated: AiSuggestionsReport["suggestions"] = [];

    for (const gap of listContentGaps({ moduleId, limit: 3 })) {
      generated.push(
        storeAiSuggestion({
          id: `aisug-gap-${gap.id}`,
          kind: "content-rewrite",
          title: `Genereer content over ${gap.topic}`,
          rationale: gap.reason,
          suggestedTask: "knowledge.write",
          priority: gap.priority === "high" || gap.priority === "critical" ? "high" : "medium",
          status: "pending",
          generatedAt: context.now,
          moduleId,
        }),
      );
    }

    for (const score of listQualityScores({ moduleId, limit: 10 }).filter((entry) => entry.overall < 75)) {
      generated.push(
        storeAiSuggestion({
          id: `aisug-quality-${score.contentId}`,
          kind: "quality-fix",
          title: `Kwaliteitsverbetering voor ${score.contentId}`,
          rationale: `Score ${score.overall}/100 — Atlas AI kan een review- of rewrite-taak uitvoeren.`,
          suggestedTask: "knowledge.review",
          targetContentId: score.contentId,
          priority: "high",
          status: "pending",
          generatedAt: context.now,
          moduleId,
        }),
      );
    }

    const readyForAiPipeline = generated.filter((entry) => entry.status === "pending" && entry.suggestedTask);

    return {
      analyzerId: "ai-suggestions.synthesizer",
      category: "ai-suggestions",
      generatedAt: context.now,
      confidence: generated.length > 0 ? 0.78 : 0.35,
      data: {
        generatedAt: context.now,
        suggestions: generated,
        readyForAiPipeline,
      },
      metadata: {
        note: "Suggestions are structured for Atlas AI Router — not generated by a model in this layer.",
      },
    };
  },
};
