export type AiSuggestionKind =
  | "prompt-improvement"
  | "content-rewrite"
  | "structure-change"
  | "quality-fix"
  | "link-suggestion"
  | "translation"
  | "seo";

export type AiSuggestionStatus = "pending" | "accepted" | "dismissed" | "applied";

/** Structured suggestions for Atlas AI or editors — NOT generated by an AI model here. */
export type AiSuggestion = {
  id: string;
  kind: AiSuggestionKind;
  title: string;
  rationale: string;
  suggestedTask?: string;
  targetContentId?: string;
  priority: "low" | "medium" | "high";
  status: AiSuggestionStatus;
  generatedAt: string;
  moduleId?: string;
};

export type AiSuggestionsReport = {
  generatedAt: string;
  suggestions: AiSuggestion[];
  readyForAiPipeline: AiSuggestion[];
};
